<?php
    $_REQUEST = $this->getRequest()->getParams();
    
    $wlc = isset($_REQUEST['webengage_license_code']) ? htmlspecialchars($_REQUEST['webengage_license_code'], ENT_COMPAT, 'UTF-8') : "";
    $vm = isset($_REQUEST['verification_message']) ? htmlspecialchars($_REQUEST['verification_message'], ENT_COMPAT, 'UTF-8') : "";
    $wwa = isset($_REQUEST['webengage_widget_status']) ? htmlspecialchars($_REQUEST['webengage_widget_status'], ENT_COMPAT, 'UTF-8') : "";
    if(isset($wlc)){
        ?>
            <form  target="_top" id="postbackToWp" name="postbackToWp" method="post" action="<?php echo Mage::helper('webengage_coup')->getUrlWrapper($this->getFormAction()) . "?noheader=true"; ?>">
                <input type="hidden" name="weAction" value="wp-save"/>
                <input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>" />
                <input type="hidden" name="verification_message" value="<?php echo $vm; ?>"/>
                <input type="hidden" name="webengage_license_code" value="<?php echo $wlc; ?>"/>
                <input type="hidden" name="webengage_widget_status" value="<?php echo $wwa; ?>"/>                   
            </form>
            <script type="text/javascript">
                document.getElementById("postbackToWp").submit();
            </script>
    <?php
    }       
    exit;
?>
